force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupMember__c/GroupMember__c.object-meta.xml
<CustomObject>
    <label>GroupMember</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GroupMember Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupMember__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>GroupMember</relationshipLabel>
    <relationshipName>GroupMember</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GroupMember__c/fields/memberRole__c.field-meta.xml
<CustomField>
    <fullName>memberRole__c</fullName>
    <label>memberRole</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>memberType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>企业业务部长</fullName>
            </value>
            <value>
                <fullName>渠道业务主管</fullName>
            </value>
            <value>
                <fullName>生态合作leader</fullName>
            </value>
            <value>
                <fullName>代表处代表</fullName>
            </value>
            <value>
                <fullName>相关行业主管</fullName>
            </value>
            <value>
                <fullName>MKT销售部主管</fullName>
            </value>
            <value>
                <fullName>其他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GroupMember__c/fields/memberType__c.field-meta.xml
<CustomField>
    <fullName>memberType__c</fullName>
    <label>memberType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>常设成员</fullName>
            </value>
            <value>
                <fullName>决策成员</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MyHelloWorld.cls
public class MyHelloWorld{

    public List<SelectOption> groupOptions {get;set;}
    public String GroupName{get;set;}
    public List<GroupMember__c> groupMembers{get;set;}
    public List<String> values { get; set; }
    public List<SelectOption> options{get{

        return new List<SelectOption> {
            new SelectOption('test1', 'test1'),
            new SelectOption('test2', 'test2'),
            new SelectOption('test3', 'test3'),
            new SelectOption('test4', 'test4')
        };
    }set;}

    public MyHelloWorld(){
        groupOptions=new List<SelectOption>();
        groupMembers=new List<GroupMember__c>();
        values = new String[] { 'test1', 'test2' };
        Integer index=1;
        for(Group__c gr : [Select id,Name From Group__c Order by CreatedDate desc]){

            SelectOption item=new SelectOption(gr.Id,gr.Name);
            groupOptions.add(item);
            if(index==1){
                GroupName=gr.Id;
            }
            index++;
        }

        getGroupMemberByGroup();
    }

    public void getGroupMemberByGroup(){
        groupMembers=[Select id,Name,memberType__c,memberRole__c From GroupMember__c where Group__c=:GroupName];
    }

 }