force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Expense名称</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expense</relationshipLabel>
    <relationshipName>Expense</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/testController.cls
global class testController {
    public String index{get;set;}
    public String index2{get;set;}
    public String index3{get;set;}
    public String index4{get;set;}
    public Expense__c ex{get;set;}
    public static string test{get;set;}
    public testController(){}

    public void addmessage(){
    	System.debug('index:'+index);
    	System.debug('index2:'+index2);
    	System.debug('index3:'+index3);
    	System.debug('index4:'+index4);
    	/*if(index!=null){
    		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,index));
    	}*/
        Account acc=[select id from Account where Name='wang'];
        Expense__c ex=[select id,Account__c,Date__c from Expense__c where Name='test'];
        ex.Account__c=acc.Id;
        update ex;

    }

    @RemoteAction
    public static String changeTest(){
        test = 'test changed';
        return test;
    }
    global class testinner{
        global string str;
    }
}